{
 "title": "Nodeapi Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "container_name",
    "label": "container_name",
    "query": {
     "query": "container_cpu_utilized{aws_ecs_cluster_name=\"api\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$container_name | container_cpu_utilized",
   "type": "timeseries",
   "description": "container_cpu_utilized",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "container_cpu_utilized{aws_ecs_cluster_name=\"api\",aws_ecs_task_family=~\".+Postgres.+|.+Nodeapi.+|.+Index.+|.+Frontend.+\",container_name=~\"$container_name\"}",
     "legendFormat": "{{container_name}} {{container_image_name}}:{{container_image_tag}} {{aws_ecs_task_id}} {{aws_ecs_task_family}}"
    }
   ]
  },
  {
   "title": "$container_name | container_memory_utilized",
   "type": "timeseries",
   "description": "container_memory_utilized",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "container_memory_utilized{aws_ecs_cluster_name=\"api\",aws_ecs_task_family=~\".+Postgres.+|.+Nodeapi.+|.+Index.+|.+Frontend.+\",container_name=~\"$container_name\"}",
     "legendFormat": "{{container_name}} {{container_image_name}}:{{container_image_tag}} {{aws_ecs_task_id}} {{aws_ecs_task_family}}"
    }
   ]
  },
  {
   "title": "$container_name | network_rate_tx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "container_network_rate_tx{aws_ecs_cluster_name=\"api\",aws_ecs_task_family=~\".+Postgres.+|.+Nodeapi.+|.+Index.+|.+Frontend.+\",container_name=~\"$container_name\"}",
     "legendFormat": "{{container_name}} {{container_image_name}}:{{container_image_tag}} {{aws_ecs_task_id}} {{aws_ecs_task_family}}"
    }
   ]
  },
  {
   "title": "$container_name | network_rate_rx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "container_network_rate_rx{aws_ecs_cluster_name=\"api\",aws_ecs_task_family=~\".+Postgres.+|.+Nodeapi.+|.+Index.+|.+Frontend.+\",container_name=~\"$container_name\"}",
     "legendFormat": "{{container_name}} {{container_image_name}}:{{container_image_tag}} {{aws_ecs_task_id}} {{aws_ecs_task_family}}"
    }
   ]
  }
 ]
}